[2024-12-04T22:52:14.254+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T22:52:14.277+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_to_postgres manual__2024-12-04T22:52:08.978975+00:00 [queued]>
[2024-12-04T22:52:14.290+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_to_postgres manual__2024-12-04T22:52:08.978975+00:00 [queued]>
[2024-12-04T22:52:14.291+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-04T22:52:14.310+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2024-12-04 22:52:08.978975+00:00
[2024-12-04T22:52:14.320+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=372) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-04T22:52:14.322+0000] {standard_task_runner.py:72} INFO - Started process 374 to run task
[2024-12-04T22:52:14.322+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_to_postgres', 'manual__2024-12-04T22:52:08.978975+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp6v10qwir']
[2024-12-04T22:52:14.324+0000] {standard_task_runner.py:105} INFO - Job 82: Subtask load_to_postgres
[2024-12-04T22:52:14.390+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_to_postgres manual__2024-12-04T22:52:08.978975+00:00 [running]> on host f697cea74b34
[2024-12-04T22:52:14.696+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T22:52:08.978975+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T22:52:08.978975+00:00'
[2024-12-04T22:52:14.697+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-04T22:52:14.698+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-04T22:52:14.699+0000] {logging_mixin.py:190} INFO - Current task name:load_to_postgres state:running start_date:2024-12-04 22:52:14.278725+00:00
[2024-12-04T22:52:14.700+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-12-04T22:52:14.701+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T22:52:14.726+0000] {base.py:84} INFO - Retrieving connection 'postgres_conn'
[2024-12-04T22:52:14.775+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 29, in load_to_postgres
    for row in data:
               ^^^^
TypeError: 'NoneType' object is not iterable
[2024-12-04T22:52:14.794+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-04T22:52:14.795+0000] {logging_mixin.py:190} INFO - Task start:2024-12-04 22:52:14.278725+00:00 end:2024-12-04 22:52:14.793849+00:00 duration:0.515124
[2024-12-04T22:52:14.796+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_to_postgres> dag:<DAG: etl_pipeline> dagrun:<DagRun etl_pipeline @ 2024-12-04 22:52:08.978975+00:00: manual__2024-12-04T22:52:08.978975+00:00, state:running, queued_at: 2024-12-04 22:52:09.020705+00:00. externally triggered: True>
[2024-12-04T22:52:14.797+0000] {logging_mixin.py:190} INFO - Failure caused by 'NoneType' object is not iterable
[2024-12-04T22:52:14.798+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=load_to_postgres, run_id=manual__2024-12-04T22:52:08.978975+00:00, execution_date=20241204T225208, start_date=20241204T225214, end_date=20241204T225214
[2024-12-04T22:52:14.817+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T22:52:14.818+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 82 for task load_to_postgres ('NoneType' object is not iterable; 374)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline.py", line 29, in load_to_postgres
    for row in data:
               ^^^^
TypeError: 'NoneType' object is not iterable
[2024-12-04T22:52:14.861+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-04T22:52:14.888+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T22:52:14.894+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
